### ISSUE TITLE
Listen address for graphite-web

### ISSUE THREAD

**Issue by jmprice** [pivotalservices/grafana-all-in-one-release#1]
Any chance you can add the ability to specify the listen address for graphite-web or at least the ability to have it listen on 127.0.0.1 only?

Something like this in graphite-vhost.conf.erb

<VirtualHost <%= p('graphite-web.httpd.listen_addr') %>:<%= p('graphite-web.httpd.port') %>>

**Comment by sneal** [comment]
@jmprice Do you just want the ability to lock down the web interface to the local machine? If so, I'd be fine making that configurable as long as the default was is as it is today. We typically access the web component from another machine.

Would you mind submitting a PR for this?

**Comment by sneal** [comment]
Fixed by #2
